before: 
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates: 
      - 'ghcr.io/middleware-labs/agent-host-go:{{ .Version }}'
    dockerfile: Dockerfile
    extra_files:
      - configyamls/all/otel-config.yaml
      - configyamls/nodocker/otel-config.yaml

changelog:
  skip: true

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: middleware-labs
    name: agent-host-go 
  # skip_upload: true      

snapcrafts:
  - name: mw-agent-host
    publish: true
    channel_templates:
      - latest/stable
    summary: test-summary
    description: | 
      test-description
    base: core20
    grade: stable
    confinement: strict
    


    
      


