apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: integration-test
  name: integration-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: integration-test
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.30.0 (9d8dcb518)
      labels:
        io.kompose.network/kafka-stack-docker-compose-default: "true"
        io.kompose.service: integration-test
    spec:
      containers:
        - env:
            - name: KAFKA_BOOTSTRAP_SERVER
              value: ${KAFKA_BOOTSTRAP_SERVER}
          image: ghcr.io/middleware-labs/integration-test:dp
          imagePullPolicy: Always
          name: integration-test
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: integration-test
  name: integration-test
  namespace: default
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: integration-test
