name: mw-agent-host # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  mw-agent-host:
    command: bin/mw-agent-host

parts:
  mw-agent-host:
    # See 'snapcraft plugins'
    plugin: go
    source: .
    build-packages:
      - pkg-config
      - libssl-dev
    # source-branch: keval-temp
    # source: https://github.com/middleware-labs/agent-host.git
