name: Build & Push Go APT Package

on:
  push:
    # branches:
    #   - 'dev'

    tags:
      - 'aws*'

env:
  ARCH: all
  BINARY_SOURCE: release/mw-go-agent-host-aws
  BINARY_NAME: mw-go-agent-host-aws
  BINARY_TEST: update
  RELEASE_VERSION: 0.0.15

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    - name: Creating Required Folder Structure
      run: |
        mkdir -p ~/rpmbuild/BUILD
        mkdir -p ~/rpmbuild/BUILDROOT
        mkdir -p ~/rpmbuild/RPMS
        mkdir -p ~/rpmbuild/SOURCES
        mkdir -p ~/rpmbuild/SPECS
        mkdir -p ~/rpmbuild/SRPMS
        mkdir -p ~/rpmbuild/SOURCES/mw-go-agent-host-aws-0.0.1
        echo '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros
        touch ~/rpmbuild/SPECS/$BINARY_NAME.spec
        cp installables/rpmessentials/$BINARY_NAME.spec ~/rpmbuild/SPECS/$BINARY_NAME.spec

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Go Build
      run: |
        go build -v -o $BINARY_NAME ~/rpmbuild/SOURCES/mw-go-agent-host-aws-0.0.1/
        tar -czvf ~/rpmbuild/SOURCES/$BINARY_NAME_0.0.1.tar.gz ~/rpmbuild/SOURCES/mw-go-agent-host-aws-0.0.1/

    - name: Create RPM package
      run: |
        rpmbuild -ba ~/rpmbuild/SPECS/$BINARY_NAME.spec

    - name: Upload artifacts to Github Pages (install.middleware.io)
      run: |

        git clone https://.:${{ secrets.GHCR_TOKEN }}@github.com/middleware-labs/install.middleware.io.git
        cp -r ~/rpmbuild/RPMS/x86_64/mw-go-agent-host-aws-0.0.1-1.x86_64.rpm install.middleware.io/rpms
        cd install.middleware.io
        git config --global user.email "keval@middleware.io"
        git config --global user.name "bhogayatakb"
        git add .
        git commit -m "RPM added to install.middleware.io"
        git push origin master
