name: Build Docker image Windows

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Setting Release Number
        run: |
          if [ -n "${{ github.event.inputs.release_version }}" ]; then
            echo "RELEASE_VERSION=${{ github.event.inputs.release_version }}" >> $GITHUB_ENV
          else
            echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          dockerfile: Dockerfiles/DockerfileWindows
          context: .
          push: true
          tags: | 
            windows-$RELEASE_VERSION
            ghcr.io/middleware-labs/agent-host-go:windows-${{ github.sha }}
          platforms: windows/amd64
