name: Docker build suitable for Linux amd64, arm64

on:
  workflow_dispatch:
    inputs:
        tag:
          description: 'Tag for Docker image'
          required: true
  push:
    paths-ignore:
      - '.github/**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  push_to_docker_registry:
    name: Build & Push Docker Image for Host Agent
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GHCR_TOKEN }}
          ssh-key: ${{ secrets.CHECK_AGENT_ACCESS }}
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }} # Consists Github Personal Access Token

      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/middleware-labs/mw-host-agent    

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: DockerfileLinux
          push: true
          platforms: linux/amd64,linux/arm64
          tags: | 
            ${{  github.event.inputs.tag || steps.meta.outputs.tags }}