name: Multi Agent Docker Build & Push - Kube Agent + OpsAI + Synthetics

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for Docker image'
        required: true
      platform:
        description: 'Platform to build the Docker image for (amd64, arm64, or both)'
        required: true
        default: 'both'
  push:
    paths-ignore:
      - '.github/**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_and_push:
    name: Build & Push Docker Images (Matrix)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        agent:
          - name: kube-agent
            binary: mw-kube-agent
            dockerfile: Dockerfiles/DockerfileKube.base
            image: ghcr.io/middleware-labs/mw-kube-agent
          - name: opsai
            binary: mw-opsai
            dockerfile: Dockerfiles/DockerfileKube.base
            image: ghcr.io/middleware-labs/mw-opsai
          - name: synthetics
            binary: mw-synthetics
            dockerfile: Dockerfiles/DockerfileKube.base
            image: ghcr.io/middleware-labs/mw-synthetics
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GHCR_TOKEN }}
          ssh-key: ${{ secrets.CHECK_AGENT_ACCESS }}
          submodules: 'recursive'

      - name: Set up GOPRIVATE
        run: echo "GOPRIVATE=your.private.repo" >> $GITHUB_ENV

      - name: Caching Go Modules and Build Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.agent.image }}

      - name: Setting Release Number
        run: |
          if [ -n "${{ github.event.inputs.release_version }}" ]; then
            echo "RELEASE_VERSION=${{ github.event.inputs.release_version }}" >> $GITHUB_ENV
          else
            echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi

      - name: Setting Platforms
        id: set-platforms
        run: |
          if [[ "${{ github.event.inputs.platform }}" == "amd64" ]]; then
            echo "PLATFORMS=linux/amd64" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.platform }}" == "arm64" ]]; then
            echo "PLATFORMS=linux/arm64" >> $GITHUB_ENV
          else
            echo "PLATFORMS=linux/amd64,linux/arm64" >> $GITHUB_ENV
          fi

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ${{ matrix.agent.dockerfile }}
          push: true
          platforms: ${{ env.PLATFORMS }}
          build-args: |
            AGENT_VERSION=${{ env.RELEASE_VERSION }}
            GITHUB_TOKEN=${{ secrets.GHCR_TOKEN }}
            APP_BINARY=${{ matrix.agent.binary }}
          tags: |
            ${{ matrix.agent.image }}:${{ env.RELEASE_VERSION }}
